### ISSUE TITLE
Blowfish on STM32F4Discovery

### ISSUE THREAD

**Issue by pietrobiondi** [odzhan/tinycrypt#1]
Hello,
I tried to import the Blowfish algorithm into my STM32 board.

Compilation and flash steps are successful. 
Unfortunately, the execution fails in my board since the board crashes on the _"bf_setkey"_ call function.

Can you give me some advice to have the Blowfish working on the stm32 board?

Thanks

**Comment by odzhan** [comment]
I'll have a look at code now.

**Comment by pietrobiondi** [comment]
Hi,
thanks for you updates. However, still the board doesn't end the blowfish algorithm. I debuged a bit and I noticed that the board crashes when it computes row 375 (invocation of BF_Encrypt inside BF_set_key).
In particulat, the board crashes when it executes the for loop of line 321. So, when it invokes the BF_round instruction.

I changed a bit the code for testing, and I noticed that limiting the "for" loop (line 321 to 3 iterations allows the board to complete the algorithm.

At this point, it seems an issue related to the HW resoureces of the board. So, please do you have any idea how to simplify the code to make blowfish working?

Thanks for your support.

**Comment by odzhan** [comment]
I would love to help you, but I honestly have no idea why it crashes. Resource exhaustion seems like the core problem. Blowfish isn't suitable for resource constrained environments like the board you're working with. It requires a lot of RAM and ROM for the lookup tables. I would recommend using AES instead because it can be implemented efficiently on 8-bit and 32-bit architectures with or without table lookups. If you **really** need to use Blowfish, and I can't see why, then I would try some other implementation like this: https://tls.mbed.org/blowfish-source-code

**Comment by pietrobiondi** [comment]
I understand your explaination. 
My point is that I need to develop an application that encrypts 64bits and provide as output an encrypted text of 64bits. 
This is way I need a cypher like blowfish. I've already tried AES and it properly works but generates 128bits of outputs. 
Can you suggest a valid alternative, less computational hungry, than blowfish?

**Comment by odzhan** [comment]
For 64-bit alternatives, I would recommend: SPECK-64/128, XTEA, RC5, RoadRunneR. I'm guessing this is a school project so SPECK64-128 is a good choice. It has low RAM and ROM requirements. https://github.com/odzhan/tinycrypt/blob/master/block/speck/speck64.c
